In [1]:
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')
import seaborn as sns
import pandas as pd

In [2]:
maxi = pd.read_csv('hr_rr_t_ag_dbp_sbp_age_gender_mortality_elixhauser_hem_urea_urine_rdw_abp.csv')

maxi.columns

Index(['SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'HR_MEAN', 'HR_MEDIAN', 'HR_STD',
       'HR_MIN', 'HR_MAX', 'HR_COUNT', 'RR_MEAN', 'RR_MEDIAN', 'RR_STD',
       'RR_MIN', 'RR_MAX', 'RR_COUNT', 'TEMP_MEAN', 'TEMP_MEDIAN', 'TEMP_STD',
       'TEMP_MIN', 'TEMP_MAX', 'TEMP_COUNT', 'AGE', 'GENDER', 'GENDER_BINARY',
       'AG_MEAN', 'AG_MEDIAN', 'AG_STD', 'AG_MIN', 'AG_MAX', 'AG_COUNT',
       'SYSBP_MEAN', 'SYSBP_MEDIAN', 'SYSBP_STD', 'SYSBP_MIN', 'SYSBP_MAX',
       'SYSBP_COUNT', 'DIASBP_MEAN', 'DIASBP_MEDIAN', 'DIASBP_STD',
       'DIASBP_MIN', 'DIASBP_MAX', 'DIASBP_COUNT', 'MORTALITY_INHOSPITAL',
       'MORTALITY_90DAY', 'MORTALITY_180DAY', 'comorbidity_score',
       'age_adj_comorbidity_score', 'HEM_MEAN', 'HEM_MEDIAN', 'HEM_STD',
       'HEM_MIN', 'HEM_MAX', 'HEM_COUNT', 'UREA_MEAN', 'UREA_MEDIAN',
       'UREA_STD', 'UREA_MIN', 'UREA_MAX', 'UREA_COUNT', 'URINE_OUTPUT',
       'RDW_mean', 'RDW_min', 'RDW_max', 'RDW_std', 'RDW_first', 'RDW_last',
       'RDW_count', 'RDW_delta', 'MEANBP_MEAN', 'MEANBP_MEDIAN', 'MEANBP_STD',
       'MEANBP_MIN', 'MEANBP_MAX', 'MEANBP_COUNT'],
      dtype='object')

In [3]:
abdul_karim = pd.read_csv('Final_data_table_08.01.2026.csv')

In [4]:
abdul_karim

,SUBJECT_ID,HADM_ID,ICUSTAY_ID,AGE,GENDER,ETHNICITY,ADMISSION_TYPE,ADMISSION_LOCATION,INSURANCE,DIAGNOSIS,...,Neutrophils_min,Neutrophils_max,Neutrophils_mean,Lymphocytes_min,Lymphocytes_max,Lymphocytes_mean,Vasopressor_flag,Antibiotic_flag,Sedation_flag,MORTALITY_180DAY
0,3,145834,211552,76,M,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Medicare,HYPOTENSION,...,80.7,87.0,83.85,3.0,9.4,6.20,NaN,NaN,NaN,0
1,6,107064,228232,66,F,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,CHRONIC RENAL FAILURE/SDA,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0
2,9,150750,220597,41,M,UNKNOWN/NOT SPECIFIED,EMERGENCY,EMERGENCY ROOM ADMIT,Medicaid,HEMORRHAGIC CVA,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1
3,12,112213,232669,72,M,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,PANCREATIC CANCER/SDA,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1
4,17,194023,277042,47,F,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,PATIENT FORAMEN OVALE\ PATENT FORAMEN OVALE MI...,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22360,99982,151454,221194,65,M,WHITE,EMERGENCY,PHYS REFERRAL/NORMAL DELI,Medicare,TVR,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1
22361,99982,183791,239827,66,M,WHITE,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,Medicare,BIVENTRICULAR HEART FAILURE,...,70.1,73.8,71.95,17.4,20.1,18.75,1.0,0.0,1.0,1
22362,99985,176670,279638,54,M,WHITE,EMERGENCY,EMERGENCY ROOM ADMIT,Private,FEVER,...,77.4,80.5,78.95,11.7,12.3,12.00,1.0,1.0,1.0,0
22363,99991,151118,226241,47,M,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Private,DIVERTICULITIS/SDA,...,35.0,35.0,35.00,17.0,17.0,17.00,0.0,1.0,1.0,0
22364,99995,137810,229633,89,F,WHITE,ELECTIVE,PHYS REFERRAL/NORMAL DELI,Medicare,ABDOMINAL AORTIC ANEURYSM/SDA,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,0

In [5]:
columns_to_keep = [
    'ICUSTAY_ID', 'MORTALITY_INHOSPITAL', 'MORTALITY_90DAY', 'MORTALITY_180DAY',
    'AG_MEAN', 'AG_MAX', 'AG_MIN', 'AG_STD',
    'SYSBP_MIN', 'SYSBP_MEAN', 'SYSBP_STD',
    'DIASBP_MIN', 'DIASBP_MEAN',
    'AGE',
    'RR_MEAN', 'RR_MAX', 'RR_MIN',
    'TEMP_STD', 'TEMP_MIN',
    'HR_MEAN', 'HR_MAX', 'HR_STD',
    'RDW_max', 'RDW_mean', 'RDW_min', 'RDW_std',
    'age_adj_comorbidity_score',
    'MEANBP_MIN', 'MEANBP_MEAN'
]

maxi = maxi[columns_to_keep]

In [9]:
import re

# original restriction to selected columns
columns_to_keep = [
    'ICUSTAY_ID', 'MORTALITY_INHOSPITAL', 'MORTALITY_90DAY', 'MORTALITY_180DAY',
    'AG_MEAN', 'AG_MAX', 'AG_MIN', 'AG_STD',
    'SYSBP_MIN', 'SYSBP_MEAN', 'SYSBP_STD',
    'DIASBP_MIN', 'DIASBP_MEAN',
    'AGE',
    'RR_MEAN', 'RR_MAX', 'RR_MIN',
    'TEMP_STD', 'TEMP_MIN',
    'HR_MEAN', 'HR_MAX', 'HR_STD',
    'RDW_max', 'RDW_mean', 'RDW_min', 'RDW_std',
    'age_adj_comorbidity_score',
    'MEANBP_MIN', 'MEANBP_MEAN'
]

maxi = maxi[columns_to_keep]

def rename_col(col: str) -> str:
    # Turn suffixes MEAN/MIN/MAX/STD into lowercase
    col2 = re.sub(r'_(MEAN|MIN|MAX|STD)$',
                  lambda m: '_' + m.group(1).lower(),
                  col)
    # Special case for AGE
    if col2 == 'AGE':
        col2 = 'age'
    return col2

rename_map = {c: rename_col(c) for c in maxi.columns}
maxi = maxi.rename(columns=rename_map)

In [10]:
maxi

,ICUSTAY_ID,MORTALITY_INHOSPITAL,MORTALITY_90DAY,MORTALITY_180DAY,AG_mean,AG_max,AG_min,AG_std,SYSBP_min,SYSBP_mean,...,HR_mean,HR_max,HR_std,RDW_max,RDW_mean,RDW_min,RDW_std,age_adj_comorbidity_score,MEANBP_min,MEANBP_mean
0,280836,1,1,1,12.800000,14.0,12.0,1.095445,85.0,118.982143,...,103.101695,190.0,25.040447,13.1,12.925000,12.7,0.206155,22.0,57.000000,78.154763
1,206613,0,0,0,10.200000,12.0,9.0,1.303840,83.0,100.113208,...,117.653846,147.0,15.438537,12.8,12.675000,12.5,0.150000,4.0,50.333302,66.603770
2,220345,0,0,0,14.666667,16.0,12.0,2.309401,71.0,124.217391,...,56.875000,70.0,6.499084,14.4,14.166667,14.0,0.208167,19.0,51.666698,73.371986
3,254851,0,0,0,13.000000,14.0,12.0,1.000000,88.0,149.645161,...,92.716981,116.0,11.774120,13.7,12.966667,12.6,0.635085,2.0,66.000000,94.650004
4,219649,1,1,1,12.500000,13.0,12.0,0.707107,93.0,134.326087,...,59.933333,90.0,8.632391,14.3,14.200000,14.1,0.141421,13.0,71.000000,99.246376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21242,270429,0,0,0,11.400000,13.0,9.0,1.673320,65.0,109.183673,...,111.625000,134.0,11.510633,16.6,16.116667,15.8,0.299444,14.0,42.000000,73.163265
21243,201233,0,0,0,8.666667,10.0,7.0,1.527525,70.0,128.802817,...,87.218182,106.0,8.285844,12.8,12.725000,12.7,0.050000,8.0,51.000000,86.180556
21244,283653,0,0,0,7.666667,9.0,6.0,1.527525,118.0,145.444444,...,72.720000,94.0,13.516490,15.2,15.200000,15.2,0.000000,11.0,36.000000,85.255814
21245,202802,0,0,0,12.000000,12.0,12.0,NaN,72.0,108.567164,...,99.000000,144.0,14.645819,18.3,17.800000,17.2,0.556776,2.0,49.000000,70.940299
21246,275346,0,0,0,8.333333,9.0,8.0,0.577350,77.0,124.066667,...,119.673077,140.0,13.542556,14.8,14.700000,14.6,0.141421,3.0,59.000000,84.881356

In [11]:
abdul_karim['ICUSTAY_ID'].nunique()

22365

In [12]:
abdul_karim.columns

Index(['SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'AGE', 'GENDER', 'ETHNICITY',
       'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'INSURANCE', 'DIAGNOSIS',
       ...
       'Neutrophils_min', 'Neutrophils_max', 'Neutrophils_mean',
       'Lymphocytes_min', 'Lymphocytes_max', 'Lymphocytes_mean',
       'Vasopressor_flag', 'Antibiotic_flag', 'Sedation_flag',
       'MORTALITY_180DAY'],
      dtype='object', length=146)

In [13]:
columns_to_keep = ['SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'GCS_max','GCS_mean', 
                   'Lactate_min', 'Lactate_max', 'Lactate_mean', 
                   'BUN_min', 'BUN_mean', 'BUN_max', 
                   'Bilirubin_max', 'Bilirubin_mean', 
                   'Albumin_mean', 'Albumin_min', 'Albumin_max',
                   'AlkPhos_mean', 'AlkPhos_max', 'AlkPhos_min',
                   'PT_mean', 'PT_min',
                   'INR_mean', 'INR_min',
                   'Phosphate_mean', 'Phosphate_max',
                   'PaO2_mean', 'PaO2_max',
                   'aPTT_mean', 'aPTT_min']

abdul_karim = abdul_karim[columns_to_keep]

In [14]:
maxi['ICUSTAY_ID'].nunique()

21247

In [15]:
abdul_karim_maxi_df = pd.merge(abdul_karim, maxi, on='ICUSTAY_ID', how='inner')

In [16]:
abdul_karim_maxi_df['ICUSTAY_ID'].nunique()

21247

In [17]:
abdul_karim_maxi_df.columns

Index(['SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'GCS_max', 'GCS_mean',
       'Lactate_min', 'Lactate_max', 'Lactate_mean', 'BUN_min', 'BUN_mean',
       'BUN_max', 'Bilirubin_max', 'Bilirubin_mean', 'Albumin_mean',
       'Albumin_min', 'Albumin_max', 'AlkPhos_mean', 'AlkPhos_max',
       'AlkPhos_min', 'PT_mean', 'PT_min', 'INR_mean', 'INR_min',
       'Phosphate_mean', 'Phosphate_max', 'PaO2_mean', 'PaO2_max', 'aPTT_mean',
       'aPTT_min', 'MORTALITY_INHOSPITAL', 'MORTALITY_90DAY',
       'MORTALITY_180DAY', 'AG_mean', 'AG_max', 'AG_min', 'AG_std',
       'SYSBP_min', 'SYSBP_mean', 'SYSBP_std', 'DIASBP_min', 'DIASBP_mean',
       'age', 'RR_mean', 'RR_max', 'RR_min', 'TEMP_std', 'TEMP_min', 'HR_mean',
       'HR_max', 'HR_std', 'RDW_max', 'RDW_mean', 'RDW_min', 'RDW_std',
       'age_adj_comorbidity_score', 'MEANBP_min', 'MEANBP_mean'],
      dtype='object')

In [18]:
abdul_karim_maxi_df = abdul_karim_maxi_df.drop('DIAGNOSIS', axis=1)

KeyError: "['DIAGNOSIS'] not found in axis"

In [20]:
feature_df_name = 'fifth_feature_df_14_01_2026.csv'

In [21]:
abdul_karim_maxi_df.to_csv( feature_df_name, index = False)

In [23]:
x = pd.read_csv(feature_df_name)

x.head(5)

,SUBJECT_ID,HADM_ID,ICUSTAY_ID,GCS_max,GCS_mean,Lactate_min,Lactate_max,Lactate_mean,BUN_min,BUN_mean,...,HR_mean,HR_max,HR_std,RDW_max,RDW_mean,RDW_min,RDW_std,age_adj_comorbidity_score,MEANBP_min,MEANBP_mean
0,3,145834,211552,6.0,4.444444,1.3,8.8,3.800000,36.0,40.500000,...,98.925373,168.0,28.103334,15.7,15.400000,15.0,0.273861,16.0,40.000000,76.728071
1,6,107064,228232,6.0,6.000000,NaN,NaN,NaN,65.0,65.500000,...,84.791667,100.0,5.573334,17.0,16.450000,15.9,0.777817,12.0,72.666702,87.175435
2,9,150750,220597,5.0,2.600000,1.9,2.7,2.380000,17.0,18.500000,...,87.644737,111.0,8.162849,14.3,14.000000,13.8,0.264575,12.0,67.000000,98.289474
3,12,112213,232669,6.0,4.842105,1.6,15.1,8.716667,28.0,35.500000,...,83.208333,105.0,8.518311,14.9,14.625000,14.2,0.309570,7.0,73.000000,96.819444
4,17,194023,277042,6.0,5.615385,0.9,0.9,0.900000,10.0,10.666667,...,82.400000,114.0,11.049719,12.9,12.766667,12.6,0.152753,0.0,53.000000,69.714286

In [25]:
id_cols = ['ICUSTAY_ID', 'SUBJECT_ID', 'HADM_ID']
targets = ['MORTALITY_INHOSPITAL', 'MORTALITY_90DAY', 'MORTALITY_180DAY']

# Drop ID and keep only numeric columns
numeric_x = x.drop(columns=id_cols).select_dtypes(include='number')

# Correlation of all numeric columns with the 3 targets
corr = numeric_x.corr()[targets]

# (Optional) remove the targets themselves from the index
corr = corr.drop(index=targets, errors='ignore')

print(corr)   # rows: features, columns: three mortality targets

                           MORTALITY_INHOSPITAL  MORTALITY_90DAY  \
GCS_max                               -0.194751        -0.149543
GCS_mean                              -0.207911        -0.151537
Lactate_min                            0.206344         0.173474
Lactate_max                            0.228881         0.173820
Lactate_mean                           0.241588         0.188813
BUN_min                                0.205534         0.252287
BUN_mean                               0.201946         0.245549
BUN_max                                0.194075         0.233115
Bilirubin_max                          0.190146         0.183534
Bilirubin_mean                         0.190722         0.186318
Albumin_mean                          -0.142157        -0.167685
Albumin_min                           -0.151760        -0.172439
Albumin_max                           -0.129052        -0.158548
AlkPhos_mean                           0.082659         0.134779
AlkPhos_max                            0.090541         0.138891
AlkPhos_min                            0.074305         0.129176
PT_mean                                0.126919         0.146274
PT_min                                 0.111341         0.140158
INR_mean                               0.135335         0.145589
INR_min                                0.120248         0.144783
Phosphate_mean                         0.137861         0.141358
Phosphate_max                          0.152505         0.144949
PaO2_mean                             -0.075602        -0.111626
PaO2_max                              -0.052426        -0.100005
aPTT_mean                              0.116138         0.113522
aPTT_min                               0.095650         0.109443
AG_mean                                0.239377         0.226668
AG_max                                 0.228449         0.207626
AG_min                                 0.201631         0.199447
AG_std                                 0.073434         0.055286
SYSBP_min                             -0.138539        -0.121878
SYSBP_mean                            -0.084074        -0.092286
SYSBP_std                              0.066854         0.035172
DIASBP_min                            -0.104098        -0.117329
DIASBP_mean                           -0.082566        -0.103041
age                                    0.116350         0.191737
RR_mean                                0.142302         0.144566
RR_max                                 0.074783         0.063072
RR_min                                 0.074206         0.100117
TEMP_std                               0.124581         0.079106
TEMP_min                              -0.108019        -0.123714
HR_mean                                0.090737         0.074235
HR_max                                 0.114212         0.087650
HR_std                                 0.092724         0.068076
RDW_max                                0.179599         0.249723
RDW_mean                               0.175097         0.251573
RDW_min                                0.167703         0.249420
RDW_std                                0.072467         0.059660
age_adj_comorbidity_score              0.216348         0.300393
MEANBP_min                            -0.119377        -0.121915
MEANBP_mean                           -0.075192        -0.099178

                           MORTALITY_180DAY
GCS_max                           -0.132181
GCS_mean                          -0.130586
Lactate_min                        0.157342
Lactate_max                        0.153726
Lactate_mean                       0.169165
BUN_min                            0.263702
BUN_mean                           0.257366
BUN_max                            0.244471
Bilirubin_max                      0.171964
Bilirubin_mean                     0.174916
Albumin_mean                      -0.178627
Albumin_min                       -0.181630
Albumin_max                       -0.171634
AlkPhos_mean                       0.150039
AlkPhos_max                        0.152764
AlkPhos_min                        0.144914
PT_mean                            0.152709
PT_min                             0.147522
INR_mean                           0.150634
INR_min                            0.151415
Phosphate_mean                     0.144430
Phosphate_max                      0.146379
PaO2_mean                         -0.122209
PaO2_max                          -0.112189
aPTT_mean                          0.114753
aPTT_min                           0.110128
AG_mean                            0.226716
AG_max                             0.206271
AG_min                             0.202023
AG_std                             0.050749
SYSBP_min                         -0.121415
SYSBP_mean                        -0.095251
SYSBP_std                          0.036815
DIASBP_min                        -0.129981
DIASBP_mean                       -0.115249
age                                0.218220
RR_mean                            0.142984
RR_max                             0.059438
RR_min                             0.105178
TEMP_std                           0.068417
TEMP_min                          -0.127419
HR_mean                            0.064613
HR_max                             0.082648
HR_std                             0.065948
RDW_max                            0.277416
RDW_mean                           0.281509
RDW_min                            0.281800
RDW_std                            0.052323
age_adj_comorbidity_score          0.336279
MEANBP_min                        -0.125649
MEANBP_mean                       -0.110746